<?php

declare(strict_types=1);

namespace App\Models;

use App\Support\Geo\Coordinates;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\UniqueConstraintViolationException;

/**
 * The company's attendance configuration: where the company is and how far
 * from it attendance may be recorded.
 *
 * A single row, created on first use and edited from the admin panel. Three
 * values did not justify a settings package; a table row keeps them in the
 * database with the rest of the data, editable through an ordinary Filament
 * form, and a CHECK constraint on the id keeps it single.
 *
 * @property int $id
 * @property ?string $latitude
 * @property ?string $longitude
 * @property int $radius_meters
 * @property int $correction_requests_per_month
 */
#[Fillable(['latitude', 'longitude', 'radius_meters', 'correction_requests_per_month'])]
final class AttendanceSetting extends Model
{
    public const int SINGLETON_ID = 1;

    /**
     * The key is written by current(), never generated by the database.
     */
    public $incrementing = false;

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'latitude' => 'decimal:7',
            'longitude' => 'decimal:7',
            'radius_meters' => 'integer',
            'correction_requests_per_month' => 'integer',
        ];
    }

    /**
     * The one settings row, created with the default radius the first time
     * anything asks for it. Two first requests racing to create it both end
     * up reading the same row.
     */
    public static function current(): self
    {
        $existing = self::query()->find(self::SINGLETON_ID);

        if ($existing instanceof self) {
            return $existing;
        }

        try {
            return self::query()->forceCreate([
                'id' => self::SINGLETON_ID,
                'radius_meters' => (int) config('attendance.default_radius_meters'),
                'correction_requests_per_month' => (int) config('attendance.default_correction_requests_per_month'),
            ]);
        } catch (UniqueConstraintViolationException) {
            return self::query()->findOrFail(self::SINGLETON_ID);
        }
    }

    public function isConfigured(): bool
    {
        return $this->latitude !== null && $this->longitude !== null;
    }

    public function coordinates(): ?Coordinates
    {
        if (! $this->isConfigured()) {
            return null;
        }

        return new Coordinates((float) $this->latitude, (float) $this->longitude);
    }
}
