<?php

declare(strict_types=1);

namespace App\Models;

use App\Support\Attendance\WorkingHours;
use App\Support\Geo\Coordinates;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\UniqueConstraintViolationException;

/**
 * The company's attendance configuration: where the company is, how far
 * from it attendance may be recorded, and what the official working day is.
 *
 * A single row, created on first use and edited from the admin panel. A
 * handful of values did not justify a settings package; a table row keeps
 * them in the database with the rest of the data, editable through an
 * ordinary Filament form, and a CHECK constraint on the id keeps it single.
 *
 * The two working-day times are TIME columns and read as wall-clock
 * strings, never as moments: which moment "09:00" is depends on the day
 * being asked about, and workingHours() is where that question is put.
 *
 * @property int $id
 * @property ?string $latitude
 * @property ?string $longitude
 * @property int $radius_meters
 * @property int $correction_requests_per_month
 * @property string $work_starts_at
 * @property string $work_ends_at
 * @property int $late_grace_minutes
 */
#[Fillable(['latitude', 'longitude', 'radius_meters', 'correction_requests_per_month', 'work_starts_at', 'work_ends_at', 'late_grace_minutes'])]
final class AttendanceSetting extends Model
{
    public const int SINGLETON_ID = 1;

    /**
     * The key is written by current(), never generated by the database.
     */
    public $incrementing = false;

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'latitude' => 'decimal:7',
            'longitude' => 'decimal:7',
            'radius_meters' => 'integer',
            'correction_requests_per_month' => 'integer',
            'late_grace_minutes' => 'integer',
        ];
    }

    /**
     * The one settings row, created with the default radius the first time
     * anything asks for it. Two first requests racing to create it both end
     * up reading the same row.
     */
    public static function current(): self
    {
        $existing = self::query()->find(self::SINGLETON_ID);

        if ($existing instanceof self) {
            return $existing;
        }

        try {
            return self::query()->forceCreate([
                'id' => self::SINGLETON_ID,
                'radius_meters' => (int) config('attendance.default_radius_meters'),
                'correction_requests_per_month' => (int) config('attendance.default_correction_requests_per_month'),
                'work_starts_at' => (string) config('attendance.default_work_starts_at'),
                'work_ends_at' => (string) config('attendance.default_work_ends_at'),
                'late_grace_minutes' => (int) config('attendance.default_late_grace_minutes'),
            ]);
        } catch (UniqueConstraintViolationException) {
            return self::query()->findOrFail(self::SINGLETON_ID);
        }
    }

    public function isConfigured(): bool
    {
        return $this->latitude !== null && $this->longitude !== null;
    }

    public function coordinates(): ?Coordinates
    {
        if (! $this->isConfigured()) {
            return null;
        }

        return new Coordinates((float) $this->latitude, (float) $this->longitude);
    }

    /**
     * The official working day these settings describe. Unlike the
     * coordinates it always exists - the columns carry the brief's
     * 09:00–17:00 as their defaults - so no caller has to invent a working
     * day of its own when the row is fresh.
     */
    public function workingHours(): WorkingHours
    {
        return new WorkingHours(
            $this->work_starts_at,
            $this->work_ends_at,
            $this->late_grace_minutes,
        );
    }
}
